name: CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Stay on ubuntu-18.04 because of https://github.com/cca-io/rescript-material-ui/issues/141
        os: [ubuntu-18.04, windows-latest, macOS-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Yarn install
        run: yarn

      - name: JSON schema parser
        working-directory: tools/json-schema-parser
        shell: bash
        run: yarn build

      - name: Component extractor
        working-directory: tools/component-extractor
        shell: bash
        run: ./build.sh

      - name: Binding generator
        working-directory: tools/binding-generator
        shell: bash
        run: ./build.sh

      - name: Compile rescript-material-ui
        working-directory: public/rescript-material-ui
        run: yarn build

      - name: Compile rescript-material-ui-lab
        working-directory: public/rescript-material-ui-lab
        run: yarn build

      - name: Examples
        working-directory: examples
        run: yarn build
