name: CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn
        env:
          IS_BS_MATERIAL_UI_PPX_CI: true

      - name: JSON schema parser
        working-directory: tools/json-schema-parser
        shell: bash
        run: yarn build

      - name: Component extractor
        working-directory: tools/component-extractor
        shell: bash
        run: ./build.sh

      - name: Binding generator
        working-directory: tools/binding-generator
        shell: bash
        run: ./build.sh

      # Build PPX
      - name: Install esy
        run: |
          npm install -g esy@latest cross-env

      - name: Build PPX
        run: |
          cd public/rescript-material-ui-ppx
          esy

      - name: Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: public/rescript-material-ui-ppx/_build/default/src/bin.exe
        env:
          CI: true

  publish:
    if: github.event_name != 'pull_request'
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download linux artifacts
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest
          path: public/rescript-material-ui-ppx/binaries/linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@master
        with:
          name: macOS-latest
          path: public/rescript-material-ui-ppx/binaries/darwin

      - name: Download windows artifacts
        uses: actions/download-artifact@master
        with:
          name: windows-latest
          path: public/rescript-material-ui-ppx/binaries/windows

      - name: Move artifacts
        run: |
          mkdir -p public/rescript-material-ui-ppx/bin
          mv public/rescript-material-ui-ppx/binaries/darwin/bin.exe public/rescript-material-ui-ppx/bin/bs_material_ui_ppx-darwin-x64.exe
          mv public/rescript-material-ui-ppx/binaries/windows/bin.exe public/rescript-material-ui-ppx/bin/bs_material_ui_ppx-win-x64.exe
          mv public/rescript-material-ui-ppx/binaries/linux/bin.exe public/rescript-material-ui-ppx/bin/bs_material_ui_ppx-linux-x64.exe
          rm -rf public/rescript-material-ui-ppx/binaries

      - name: Publish
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          cd public/rescript-material-ui-ppx
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
