name: bs_material_ui_ppx pipeline

on:
  push:
    paths:
      - 'public/bs-material-ui-ppx/package.json'

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup
        run: |
          npm install -g esy@latest cross-env
      # OCaml 4.06 and BuckleScript 6
      - name: install-build
        run: |
          cd public/bs-material-ui-ppx
          esy install
          esy b
      - name: Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}-bsb6
          path: _build/default/src/bin.exe
      # OCaml 4.02 and BuckleScript 5
      - name: install-build @402
        run: |
          cd public/bs-material-ui-ppx
          esy @402 install
          esy @402 b
      - name: Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: _build/default/src/bin.exe
        env:
          CI: true